### ISSUE TITLE
no greek in language selection

### ISSUE THREAD

**Issue by ghost** [BlackCraze/GameResourceBot#8]
when I started hosting the bot, the two languages I could get were DE and EN? where is greek?

**Comment by PellaAndroid** [comment]
From what I can tell, the answer to your question _IS_ your question.
Where is Greek? The other languages have 19 phrases in their respective `strings_xx.xml` files. Greek has 11.
The other languages have a long list of all the resources available in the game. The `items_el.xml` file contains none.

Far be it from a know-nothing like me to speak for our lead developer. Were I a betting man, though, I'd be willing to wager that once those two files are fully populated, then Greek will take its place alongside German and English.

**Comment by ghost** [comment]
well yea, closing this isssue because PR#17 is up.
